### ISSUE TITLE
Action exits with failure even if pipeline completes successfully

### ISSUE THREAD

**Issue by ktopolski** [buildkite/trigger-pipeline-action#21]
Hello!

I'm having trouble with this action. I set up a test repository with Buildkite GitHub App and as long as I use webhook - PR is marked green, pipeline passes on buildkite, all good.

However, when I try to use this action like so(changed org name):

```
name: Buildkite test

on:
  pull_request:

jobs:
  test-buildkite:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Buildkite Pipeline
        uses: buildkite/trigger-pipeline-action@v1.2.0
        env:
          BUILDKITE_API_ACCESS_TOKEN: ${{ secrets.BUILDKITE_API_ACCESS_TOKEN }}
          PIPELINE: "karol-test-org/test-pipeline"
```

I can see my pipeline being completed successfully on Buildkite, but the action exits with error status and no further info.

Am I doing something wrong? And - is this action still maintained?

Cheers for your help!
Karol
