### ISSUE TITLE
Add support to conditionally skip triggered pipelines

### ISSUE THREAD

**Issue by migueleliasweb** [buildkite/trigger-pipeline-action#5]
Hey BK team, I have the need to create a pipeline trigger that is only called if a specific requirement is met. In my case, if a specific file was changed. I can see this pattern surge as people make their pipelines more and more dynamic.

I was thinking on something like:

```yaml

steps:
  - trigger: "<trigger-name>"
    label: "Trigger <trigger-name>"
    skip_command: ./check-specific-file-was-changed.sh
``` 

If the command return 0, the trigger should be executed. Otherwise skip.

What do you all think? Cheers!
