### ISSUE TITLE
README example needs updating.

### ISSUE THREAD

**Issue by HugeIRL** [buildkite/trigger-pipeline-action#51]
Maybe I'm not understanding something here so I'm happy to be proven wrong, but it looks like the example we have here: https://github.com/buildkite/trigger-pipeline-action#configuration-as-input-parameters doesn't actually work. 

There's a few things missing, such as`jobs:`, `build:` and `runs-on:`, as well as it seems you need to use `-` (hyphens) instead of the underscores and `buildkite-token` instead of `buildkite_api_access_token`.

I whipped up a working one below:

```
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger a Buildkite Build
        uses: "buildkite/trigger-pipeline-action@v1.6.0"
        with:
          buildkite-token: ${{ secrets.TRIGGER_BK_BUILD_TOKEN }} 
          pipeline: "my-org/my-deploy-pipeline"
          branch: "main"
          commit: "HEAD"
          message:  ":github: Triggered from a GitHub Action"
          build-env-vars: '{"TRIGGERED_FROM_GHA": "true"}'
          build-meta-data: '{"FOO": "bar"}'
          ignore-pipeline-branch-filter: true   
```

Let me know if I'm missing something obvious.
