### ISSUE TITLE
GHA action not waiting for the BK build to complete

### ISSUE THREAD

**Issue by sumitd2** [buildkite/trigger-pipeline-action#65]
Hi,

Following are the logs, even when the buildkite build is going on in the background:
Thank you.

```
Run buildkite/trigger-pipeline-action@v2.3.0
  with:
    buildkite_api_access_token: bkua_****
    pipeline: ****/ppc64le-build
    message: :github: Triggered from a GitHub Action
    build_env_vars: {"TRIGGERED_FROM_GHA": "true"}
    build_meta_data: {"FOO": "bar"}
    ignore_pipeline_branch_filter: true
    send_pull_request: true
    wait: true
    wait_interval: 60
    wait_timeout: 7200
    commit: HEAD
/usr/bin/docker run --name dfcc3bf57d8e9c9c2ec5a932b7c37b70d6e18_e18ba8 --label dfcc3b --workdir /github/workspace --rm -e "INPUT_BUILDKITE_API_ACCESS_TOKEN" -e "INPUT_PIPELINE" -e "INPUT_MESSAGE" -e "INPUT_BUILD_ENV_VARS" -e "INPUT_BUILD_META_DATA" -e "INPUT_IGNORE_PIPELINE_BRANCH_FILTER" -e "INPUT_SEND_PULL_REQUEST" -e "INPUT_WAIT" -e "INPUT_WAIT_INTERVAL" -e "INPUT_WAIT_TIMEOUT" -e "INPUT_COMMIT" -e "INPUT_BRANCH" -e "INPUT_PULL_REQUEST_BASE_BRANCH" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/milvus/milvus":"/github/workspace" dfcc3b:f7d8e9c9c2e4c5a932b7c37b70d6e18

Build created:
https://buildkite.com/****/ppc64le-build/builds/28
**Waiting for build 28 to complete...
curl: (22) The requested URL returned error: 403
Unknown build state: null
Build did not complete successfully**
```
