### ISSUE TITLE
Buildkite API call failed: "No pipeline found"

### ISSUE THREAD

**Issue by efaulhaber** [buildkite/trigger-pipeline-action#67]
I keep getting the following error:
```
curl: (22) The requested URL returned error: 404
Buildkite API call failed: "No pipeline found"
```
This is my YAML file:
https://github.com/trixi-framework/TrixiParticles.jl/blob/90861044cef321b70d2c4ac20b8792c919b0b6aa/.github/workflows/TriggerGPUTests.yml
```yml
jobs:
  trigger-buildkite:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/run-gpu-tests') }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Buildkite Pipeline
        uses: "buildkite/trigger-pipeline-action@v2.3.0"
        with:
          buildkite_api_access_token: ${{ secrets.TRIGGER_BK_BUILD_TOKEN }}
          pipeline: "julialang/trixiparticles"
          branch: ${{ github.event.pull_request.head.ref }}
          message: "Triggered from PR #${{ github.event.issue.number }} comment"
```
The pipeline clearly exists:
https://buildkite.com/julialang/trixiparticles/builds/102

I even gave the API token all available permission scopes, but it's still reporting that the pipeline could not be found.
